### PR TITLE
Fix getCollationElements behaviour with discontiguous matches

### LINKED ISSUE #5: What was wrong with the Tibetan character example?
In the TODO you mention that `0F81` becomes `0F71 0F80` under NFD, but that's the expected canonical decomposition of that character, isn't it? So I'm curious what the failing test was.

### PR DESCRIPTION
**Pull request by despresc**
This should close #5, but I couldn't find the failing test that was commented out to re-enable it.

### CODE REVIEW

**Comment by despresc** [comment]
Oh, it's in the data file itself. I'll re-enable it.

**Comment by despresc** [comment]
I suppose this fixes #6 too, now that I think about it.

**Comment by jgm** [comment]
Does it fix #6?  You haven't uncommented those commented-out lines in the test.
My recollection was that #6 had to do with pack/unpack/normalize issues, but maybe that is wrong.

**Comment by despresc** [comment]
I might have misread it. I thought it was referring to the lines in `CollationTest_SHIFTED_SHORT.txt` that I uncommented.

**Comment by jgm** [comment]
There are more commented-out lines further down, in both collation tests.  But we can take care of that separately.

**Comment by despresc** [comment]
That commit adds `getUnblockedNonStarters` back to `getCollationElements`. I think it should be slightly more efficient. I had removed it because for some reason I was worried that the rearrangement of the elements might affect what was counted as an unblocked non-starter. I realize now that it won't.

**Comment by despresc** [comment]
Actually, I think it could affect what's counted as an unblocked non-starter, at least theoretically. But one interpretation of the standard (probably the most reasonable one) requires that `getUnblockedNonStarters` be used regardless. The description of the algorithm is a little too vague in parts.

**Comment by jgm** [comment]
Agreed, I didn't find it very easy to follow the algorithm.
Thanks for this!

**Comment by despresc** [comment]
No problem. I happened to see the TODO file and was intrigued by the fact that collation was failing for such specific characters.

**Pull request merged**
